# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mrrys00/Studia/4.Semestr/Cpp/sem04-cpp-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mrrys00/Studia/4.Semestr/Cpp/sem04-cpp-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrrys00/Studia/4.Semestr/Cpp/sem04-cpp-project/CMakeFiles /home/mrrys00/Studia/4.Semestr/Cpp/sem04-cpp-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrrys00/Studia/4.Semestr/Cpp/sem04-cpp-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named pong_50th_anniversary

# Build rule for target.
pong_50th_anniversary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pong_50th_anniversary
.PHONY : pong_50th_anniversary

# fast build rule for target.
pong_50th_anniversary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/build
.PHONY : pong_50th_anniversary/fast

Actors/ball.o: Actors/ball.cpp.o
.PHONY : Actors/ball.o

# target to build an object file
Actors/ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/ball.cpp.o
.PHONY : Actors/ball.cpp.o

Actors/ball.i: Actors/ball.cpp.i
.PHONY : Actors/ball.i

# target to preprocess a source file
Actors/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/ball.cpp.i
.PHONY : Actors/ball.cpp.i

Actors/ball.s: Actors/ball.cpp.s
.PHONY : Actors/ball.s

# target to generate assembly for a file
Actors/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/ball.cpp.s
.PHONY : Actors/ball.cpp.s

Actors/paddle.o: Actors/paddle.cpp.o
.PHONY : Actors/paddle.o

# target to build an object file
Actors/paddle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/paddle.cpp.o
.PHONY : Actors/paddle.cpp.o

Actors/paddle.i: Actors/paddle.cpp.i
.PHONY : Actors/paddle.i

# target to preprocess a source file
Actors/paddle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/paddle.cpp.i
.PHONY : Actors/paddle.cpp.i

Actors/paddle.s: Actors/paddle.cpp.s
.PHONY : Actors/paddle.s

# target to generate assembly for a file
Actors/paddle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/paddle.cpp.s
.PHONY : Actors/paddle.cpp.s

Actors/score.o: Actors/score.cpp.o
.PHONY : Actors/score.o

# target to build an object file
Actors/score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/score.cpp.o
.PHONY : Actors/score.cpp.o

Actors/score.i: Actors/score.cpp.i
.PHONY : Actors/score.i

# target to preprocess a source file
Actors/score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/score.cpp.i
.PHONY : Actors/score.cpp.i

Actors/score.s: Actors/score.cpp.s
.PHONY : Actors/score.s

# target to generate assembly for a file
Actors/score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/score.cpp.s
.PHONY : Actors/score.cpp.s

Actors/wall.o: Actors/wall.cpp.o
.PHONY : Actors/wall.o

# target to build an object file
Actors/wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/wall.cpp.o
.PHONY : Actors/wall.cpp.o

Actors/wall.i: Actors/wall.cpp.i
.PHONY : Actors/wall.i

# target to preprocess a source file
Actors/wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/wall.cpp.i
.PHONY : Actors/wall.cpp.i

Actors/wall.s: Actors/wall.cpp.s
.PHONY : Actors/wall.s

# target to generate assembly for a file
Actors/wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Actors/wall.cpp.s
.PHONY : Actors/wall.cpp.s

Game/game.o: Game/game.cpp.o
.PHONY : Game/game.o

# target to build an object file
Game/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Game/game.cpp.o
.PHONY : Game/game.cpp.o

Game/game.i: Game/game.cpp.i
.PHONY : Game/game.i

# target to preprocess a source file
Game/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Game/game.cpp.i
.PHONY : Game/game.cpp.i

Game/game.s: Game/game.cpp.s
.PHONY : Game/game.s

# target to generate assembly for a file
Game/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pong_50th_anniversary.dir/build.make CMakeFiles/pong_50th_anniversary.dir/Game/game.cpp.s
.PHONY : Game/game.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... pong_50th_anniversary"
	@echo "... Actors/ball.o"
	@echo "... Actors/ball.i"
	@echo "... Actors/ball.s"
	@echo "... Actors/paddle.o"
	@echo "... Actors/paddle.i"
	@echo "... Actors/paddle.s"
	@echo "... Actors/score.o"
	@echo "... Actors/score.i"
	@echo "... Actors/score.s"
	@echo "... Actors/wall.o"
	@echo "... Actors/wall.i"
	@echo "... Actors/wall.s"
	@echo "... Game/game.o"
	@echo "... Game/game.i"
	@echo "... Game/game.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

